// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoqNFI_SAFqTMYCpbtibbLJH3LfN4RJZw',
    appId: '1:950084926594:web:8b5631770dd863b964489b',
    messagingSenderId: '950084926594',
    projectId: 'plant-guard-b4f9a',
    authDomain: 'plant-guard-b4f9a.firebaseapp.com',
    storageBucket: 'plant-guard-b4f9a.appspot.com',
    measurementId: 'G-HD6PVZ9GD5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBg_xeAIW4mRPURm6jawKM9vuusMFAy3Ao',
    appId: '1:950084926594:android:a80632594f6934b064489b',
    messagingSenderId: '950084926594',
    projectId: 'plant-guard-b4f9a',
    storageBucket: 'plant-guard-b4f9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBT065Bq0hYShI-MqVTIzJSXEhcYwrxUbo',
    appId: '1:950084926594:ios:09fccb91331a6da764489b',
    messagingSenderId: '950084926594',
    projectId: 'plant-guard-b4f9a',
    storageBucket: 'plant-guard-b4f9a.appspot.com',
    iosBundleId: 'com.example.plantGuard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBT065Bq0hYShI-MqVTIzJSXEhcYwrxUbo',
    appId: '1:950084926594:ios:09fccb91331a6da764489b',
    messagingSenderId: '950084926594',
    projectId: 'plant-guard-b4f9a',
    storageBucket: 'plant-guard-b4f9a.appspot.com',
    iosBundleId: 'com.example.plantGuard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoqNFI_SAFqTMYCpbtibbLJH3LfN4RJZw',
    appId: '1:950084926594:web:6c78732c78d2bc9764489b',
    messagingSenderId: '950084926594',
    projectId: 'plant-guard-b4f9a',
    authDomain: 'plant-guard-b4f9a.firebaseapp.com',
    storageBucket: 'plant-guard-b4f9a.appspot.com',
    measurementId: 'G-JJHK1VSNHE',
  );
}
